### ISSUE TITLE
Backup Works, Restore from backup does not

### ISSUE THREAD

**Issue by jeremyjpj0916** [gamunu/cassandra_snapshotter#4]
I am running on Cassandra 3.11.1, I have my passwordless SSH setup and all seems to be well. Except restore from backup using sseloader(automatic), seems like its having trouble connecting to my S3 on the restore only and not the backup. Backup works. 

Command to backup:

```
cassandra-snapshotter --s3-bucket-name=cassandra-backups \
                      --s3-bucket-region=company-core-1 \ 
                      --s3-base-path=cassandra-dev \ 
                      --aws-access-key-id=***** \ 
                      --aws-secret-access-key=***** \ 
                      --s3-ssenc \ 
                      backup \ 
                         --hosts=host00466,host00467,host00468,host00469,host00470,host00471 \ 
                         --user=root \ 
                         --new-snapshot
```

Works fine, I could browse my files and see the company-core-1 bucket and click into it and see
```
/cassandra-dev/{timestamp}/{hosts}/data/cassandra/data/{keyspaces}/{my_keyspace}/table-j923d239d0isdsdf/snapshots/{timestamp}/*.lzo files and such since they are compressed!
```

Now on restore I run this:

```
cassandra-snapshotter --s3-bucket-name=cassandra-backups \
                      --s3-bucket-region=company-core-1 \
                      --s3-base-path=cassandra-dev \
                      --aws-access-key-id=***** \
                      --aws-secret-access-key=***** \
                      --verbose \ 
                      restore \
                         --target-hosts=host00466,host00467,host00468,host00469,host00470,host00471 \
                         --keyspace keyspace_dev \
                         --snapshot-name 20180510214836 \
                         --restore-dir /data/tmp/cassandra_restore/ \
```

The error it throws is like so:

```
# cassandra-snapshotter --s3-bucket-name=cassandra-backups --s3-bucket-region=company-core-1 --s3-base-path=cassandra-dev --aws-access-key-id=***** --aws-secr
et-access-key=***** --verbose restore --target-hosts=host00466,host00467,host00468,host00469,host00470,host00471 --keyspace keyspace_dev --snapshot-name
 20180510214836 --restore-dir /data/tmp/cassandra_restore/
Restoring keyspace: keyspace_dev  from backup 20180510214836
Backup files of the following host(s) will be downloaded in '/data/tmp/cassandra_restore/': host00466, host00467, host00468, host00469, host00470, host00471.
After the downloading data will be streamed to the following host(s) via sstableloader: host00466, host00467, host00468, host00469, host00470, host00471.
Traceback (most recent call last):
  File "/bin/cassandra-snapshotter", line 9, in <module>
    load_entry_point('cassandra-snap==1.2.1', 'console_scripts', 'cassandra-snapshotter')()
  File "/usr/lib/python2.7/site-packages/cassandra_snap-1.2.1-py2.7.egg/cassandra_snap/main.py", line 364, in main
    restore_backup(args)
  File "/usr/lib/python2.7/site-packages/cassandra_snap-1.2.1-py2.7.egg/cassandra_snap/main.py", line 157, in restore_backup
    worker.restore(args.keyspace, args.table, hosts, target_hosts)
  File "/usr/lib/python2.7/site-packages/cassandra_snap-1.2.1-py2.7.egg/cassandra_snap/snapshotting.py", line 148, in restore
    for k in bucket.list(self.snapshot.base_path):
  File "/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/bucket.py", line 474, in get_all_keys
    '', headers, **params)
  File "/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/bucket.py", line 412, in _get_all
    response.status, response.reason, body)

boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden

<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>The AWS Access Key Id you provided does not exist in our records.</Message>
<AWSAccessKeyId>**************************</AWSAccessKeyId>
<RequestId>********************</RequestId>
<HostId>********************************************</HostId>
</Error>
```

@gamunu I'm not sure what steps really are next to take. I 100% know I am passing the same
```
--aws-access-key-id=***** \
--aws-secret-access-key=***** \
```
In the requests, any ideas here or if you have suggestions for me to add some print statements and where/what object I will do so and report back to you. Any help is certainly appreciated, it seemed magical watching it do the backups successfully(which is half the battle) , now we just need restore and I will be all set!

-Jeremy

**Comment by jeremyjpj0916** [comment]
I have begun to investigate further. Here are my findings thus far:

On snappshotter.py I added some debug print statements around line 148 to see some variable results:

```
        for name in vars().keys():
           print(name)
           
        for value in vars().values():
           print(value)

        for k in bucket.list(self.snapshot.base_path):
            r = self.keyspace_table_matcher.search(k.name)
```


```
matcher_string
tables
target_hosts
keys
self
bucket
keyspace
hosts
table_log
snap_name
table
(host00466|host00467|host00468|host00469|host00470|host00471).*/(keyspace_dev)/(.*?-?[A-Za-z0-9]*)/
set([])
['host00466', 'host00467', 'host00468', 'host00469', 'host00470', 'host00471']
[]
<cassandra_snap.snapshotting.RestoreWorker object at 0x31f5d50>
<Bucket: cassandra-backups>
S3Connection:s3.amazonaws.com
keyspace_dev
[u'host00466', u'host00467', u'host00468', u'host00469', u'host00470', u'host00471']
20180510214836
.*?
20180510214836
Traceback (most recent call last):
```
The biggest thing that sticks out to me is the S3Connection saying: s3.amazonaws.com, should that be saying the hostname of the connection param I put in the restore request?

utils I have something like this for my custom company internal s3
```
S3_CONNECTION_HOSTS = {
    'company-core-1': 'ooss.company.com',
    'company-dmz-1': 'dooss.company.com'
    '''
    'us-east-1': 's3.amazonaws.com',
    'us-west-2': 's3-us-west-2.amazonaws.com',
    'us-west-1': 's3-us-west-1.amazonaws.com',
    'eu-central-1': 's3-eu-central-1.amazonaws.com',
    'eu-west-1': 's3-eu-west-1.amazonaws.com',
    'ap-southeast-1': 's3-ap-southeast-1.amazonaws.com',
    'ap-southeast-2': 's3-ap-southeast-2.amazonaws.com',
    'ap-northeast-1': 's3-ap-northeast-1.amazonaws.com',
    'ap-south-1': 's3.ap-south-1.amazonaws.com',
    'sa-east-1': 's3-sa-east-1.amazonaws.com',
    'cn-north-1': 's3.cn-north-1.amazonaws.com.cn'
    '''
}
```

Thanks.

**Comment by jeremyjpj0916** [comment]
Figured it out @gamunu , can you make the code change to populate this dynamically? the restore script logic needs this @ line 103 in snapshotting.py:

```
        self.s3connection = S3Connection(
            aws_access_key_id=self.aws_access_key_id,
            aws_secret_access_key=self.aws_secret_access_key,
            host='ooss.company.com')
```
Where host='ooss.company.com' should be the dynamic selected one from the list of S3_CONNECTION_HOSTS in utils, with it defaulted as is it just uses the boto default. 

EDIT - Made 2 PR's with the file changes, take a look and merge em both to get the fix 👍 

Further problems though...

```
invoking: /usr/bin/sstableloader --nodes host00466,host00467,host00468,host00469,host00470,host00471 -v                 /data/tmp/cassandra_restore/keyspace_dev/services-ff9dbcc031fb11e8b
5a2b7b5312a40dc
sh: /usr/bin/sstableloader: No such file or directory
Restore completed.
```

I found that the /user/bin/sstableloader does not exist, but doing a which showed it to be in the /bin/sstableloader , so next step is to see where in the code you are hard coding that I suppose and see if we can change it a bit. 

I am adding something like this here now, if you can make that bin path an argument in on restore that would work great for me 👍  :
```
        if target_hosts and self.run_sstableloader:
            self._run_sstableloader(keyspace_path, tables, target_hosts,
                                    '/bin')
logging.info("Restore completed.")
```

EDIT - Oh crap... sstableloader runs on the Node orchestrating these backups/restores... what if the node orchestrating these backups and restores was not a c* node xD ..... can i install sstableloader by itself on this node and then it can do it??? oh man I was hoping this thing remote hosted into each c* node and sstableloader on the nodes themselves, hmmmmm let me rerun this restore from one of the stage C* nodes themselves.

**Comment by gamunu** [comment]
Thanks for the pull requests. Right now I don't have time to do testing, I'll merge these asap probably will integrate Travis later.

**Comment by jeremyjpj0916** [comment]
Sure, that sounds good. Question for you. Since restore runs like this:

```
 /bin/sstableloader --nodes host00466,host00467,host00468,host00469,host00470,host00471 -v              /data/tmp/cassandra_restore/keyspace_dev/table-ff9dbcc031fb11e8b5a2b
```
So is it okay to run this from one of the --nodes that we intend to restore too? I imagine restore is supposed to be ran on all hosts in the cluster you intend to restore your backups from. Basically I want to know can I run restore from a C* node on my cluster and reference my own node too in the nodes? Also seems large portion of the args needed by this app are not there? Don't we need to specify a YAML and TLS options and all sorts of such?

```
Short option | Long option | Description
-- | -- | --
-alg | --ssl-alg <ALGORITHM> | Client SSL algorithm (default: SunX509).
-ap | --auth-provider <auth provider class                                 name> | Allows the use of a third party auth provider. Can be combined                                 with -u <username> and -pw <password> if the auth provider                                 supports plain text credentials.
-ciphers | --ssl-ciphers <CIPHER-SUITES> | Client SSL. Comma-separated list of encryption suites.
-cph | --connections-per-host <connectionsPerHost> | Number of concurrent connections-per-host.
-d | --nodes <initial_hosts> | Required. Connect to a list of (comma separated) hosts for                                 initial cluster information.
-f | --conf-path <path_to_config_file> | Path to the cassandra.yaml path for                                 streaming throughput and client/server SSL.
-h | --help | Display help.
-i | --ignore <NODES> | Do not stream to this comma separated list of nodes.
-ks | --keystore <KEYSTORE> | Client SSL. Full path to the keystore.
-kspw | --keystore-password                                 <KEYSTORE-PASSWORD> | Client SSL. Password for the keystore.                                  Overrides the client_encryption_options option                                     in cassandra.yaml
  | --no-progress | Do not display progress.
-p | --port <rpc port> | RPC port (default: 9160 [Thrift]).
-prtcl | --ssl-protocol <PROTOCOL> | Client SSL. Connections protocol to use (default: TLS). Overrides the server_encryption_options option                                 in cassandra.yaml
-pw | --password <password> | Password for Cassandra authentication.
-st | --store-type <STORE-TYPE> | Client SSL. Type of store.
-t | --throttle <throttle> | Throttle speed in Mbits (default: unlimited). Overrides the                                 stream_throughput_outbound_megabits_per_sec                                 option in cassandra.yaml
-tf | --transport-factory <transport                                 factory> | Fully-qualified ITransportFactory class name                                 for creating a connection to Cassandra.
-ts | --truststore <TRUSTSTORE> | Client SSL. Full path to truststore.
-tspw | --truststore-password                                 <TRUSTSTORE-PASSWORD> | Client SSL. Password of the truststore.
-u | --username <username> | User name for Cassandra authentication.
-v | --verbose | Verbose output.
```
EDIT - Actually you know what, I think it makes sense to just do a local restore script that executes local restore commands for every C* node. after the files are local to my nodes s mv command on the dir can be done right away without scrubbing extra files out it seems to go into my temp dir and mv /keyspace/... to /data/cassandra/keysace or w/e ...
